import type { Metadata } from "next";
import { Geist, Geist_Mono, Suranna, Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import VisitorInitializer from "@/components/VisitorInitializer";

const suranna = Suranna({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-suranna",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Herbalur",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${suranna.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <VisitorInitializer/>
        <Header/>
        <main className="pt-[99px] lg:pt-[131px]">
          {children}
        </main>
        <Footer/>
        </body>
    </html>
  );
}
